CREATE TABLE `#__property_information` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `asset_id` int(11) NOT NULL,
  `formatted_address` text NOT NULL,
  `address_components` text NOT NULL,
  `geometry` text NOT NULL,

  `forsale_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `forsale_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `forsale_price` float NOT NULL DEFAULT '0',
  `sold_price` float unsigned NOT NULL DEFAULT '0',
  `sold_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `size` int(11) unsigned NOT NULL DEFAULT '0',
  `size_unit` varchar(45) NOT NULL DEFAULT 'sqm',
  `type` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'The catid to the property_types',
  `condition` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'The catid for the property conditions',
  `suburbs` varchar(255) NOT NULL COMMENT 'Comma separated list of suburb catid''s in which this proprty might be in.',
  `bedrooms` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `bathrooms` decimal(10,0) unsigned NOT NULL DEFAULT '1',
  `parking` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT 'The number of parking spaces available for this unit. This would also include number of garage spaces.',
  `parking_type` varchar(45) NOT NULL DEFAULT 'street' COMMENT 'This is garage, carport, parking spaces from parking lot or street, etc.',
  `features` text NOT NULL COMMENT 'Comma-separated list of catid\'s that represent the list of property Features ',

  `state` tinyint(3) NOT NULL DEFAULT '0',
  `sectionid` int(10) unsigned NOT NULL DEFAULT '0',
  `catid` int(10) unsigned NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(10) unsigned NOT NULL DEFAULT '0',
  `created_by_alias` varchar(255) NOT NULL DEFAULT '',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `images` text NOT NULL,
  `files` text NOT NULL,
  `attribs` varchar(5120) NOT NULL,
  `params` varchar(5120) NOT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `parentid` int(10) unsigned NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL DEFAULT '0',
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `access` int(10) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `metadata` text NOT NULL,
  `featured` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Set if article is featured.',
  `language` char(7) NOT NULL COMMENT 'The language code for the article.',
  `xreference` varchar(50) NOT NULL COMMENT 'A reference to enable linkages to external data sets.',
  PRIMARY KEY (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_state` (`state`),
  KEY `idx_catid` (`catid`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_featured_catid` (`featured`,`catid`),
  KEY `idx_language` (`language`),
  KEY `idx_xreference` (`xreference`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;